<a href="https://colab.research.google.com/github/TanishaGanguli/Ml-Artificial-neuron-layer/blob/main/IntroToML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

L^2 NORM


In [ ]:
import numpy as np


In [ ]:
x=np.array({25,2,5})
x

array({25, 2, 5}, dtype=object)

In [ ]:
(25**2+2**2+5**2)**(1/2)

25.573423705088842

In [ ]:
np.linalg.norm(x)

TypeError: ignored

L1 NORM

In [ ]:
x

array({25, 2, 5}, dtype=object)

In [ ]:
np.abs(25)+np.abs(2)+np.abs(5)

32

SQUARED L2 NORM

In [ ]:
X

NameError: ignored

In [ ]:
x

array({25, 2, 5}, dtype=object)

In [ ]:
(25**2+2**2+5**2)

654

In [ ]:
np.dot(x,x)

TypeError: ignored

MAX NORM

In [ ]:
x

array({25, 2, 5}, dtype=object)

In [ ]:
np.max([np.abs(25),np.abs(2),np.abs(5)])

25

BASIS,ORTHOGONAL AND ORTHONORMAL VECTORS

In [ ]:
i=np.array([1,0])
i

array([1, 0])

In [ ]:
j=np.array([0,1])
j

array([0, 1])

In [ ]:
np.dot(i,j)

0

MATRIX TENSORS

In [ ]:
X=np.array([[25,2],[5,26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [ ]:
X.shape

(3, 2)

In [ ]:
X.size

6

In [ ]:
#select left column of matrix X ( because python is zero-indexed)
X[:,0]

array([25,  5,  3])

In [ ]:
#select middle row of the matrix
X[1,:]

array([ 5, 26])

In [ ]:
#Another slicing-by-index example:
X[0:2,0:2]

array([[25,  2],
       [ 5, 26]])

MATRICES IN PyTorch

In [ ]:
import torch
import numpy
import matplotlib.pyplot as plt

In [ ]:
X_pt= torch.tensor([[25,2],[5,26],[3,7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [ ]:
X_pt.shape

torch.Size([3, 2])

In [ ]:
X_pt[1,:]

tensor([ 5, 26])

MATRICES IN TensorFlow

In [ ]:
X_tf= tf.Variable([[25,2],[5,26],[3,7]])
X_tf

NameError: ignored

In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
import tensorflow as tf
print(tensorflow.__version__)

1.15.2


In [ ]:
X_tf= tf.Variable([[25,2],[5,26],[3,7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32_ref>

In [ ]:
tf.rank(X_tf)

<tf.Tensor 'Rank:0' shape=() dtype=int32>

In [ ]:
tf.shape(X_tf)

<tf.Tensor 'Shape:0' shape=(2,) dtype=int32>

In [ ]:
X_tf[1,:]

<tf.Tensor 'strided_slice:0' shape=(2,) dtype=int32>

GENERIC TENSOR NOTATION

In [ ]:
images_pt = torch.zeros([32,28,28,3])

NameError: ignored

In [ ]:
import torch
import numpy
import matplotlib.pyplot as plt
%tensorflow_version 1.x
import tensorflow as tf
print(tensorflow.__version__)


TensorFlow 1.x selected.


NameError: ignored

In [ ]:
images_pt = torch.zeros([32,28,28,3])

In [ ]:
images_pt  #this will give you te result of how it looks like

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [ ]:
images_tf =tf.zeros([32,28,28,3])

In [ ]:
images_tf #running it will give you the result.

<tf.Tensor 'zeros:0' shape=(32, 28, 28, 3) dtype=float32>

In [ ]:
import numpy as np

In [ ]:
a=np.array([[25,2,-3,-23]])
a

array([[ 25,   2,  -3, -23]])

In [ ]:
a.T

array([[ 25],
       [  2],
       [ -3],
       [-23]])

In [ ]:
b=np.array([[42,4,7,99],[-99,-3,17,22]])

In [ ]:
b

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [ ]:
b.size

8

In [ ]:
b.shape

(2, 4)

TENSOR TRANSPOSITION

In [ ]:
X

NameError: ignored

In [ ]:
x

NameError: ignored

In [ ]:
x=np.array([[25,2],[5,26,3,7]])
x

NameError: ignored

In [ ]:
import numpy as np
import torch
import matplotlib.pyplot as plt
%tensorflow_version 1.x
import tensorflow as tf

TensorFlow 1.x selected.


In [ ]:
x=np.array([[25,2],[5,26],[3,7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [ ]:
x.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [ ]:
tf.transpose(x_tf)

NameError: ignored

In [ ]:
x_tf=tf([[25,2],[5,26],[3,7]])
x_tf

TypeError: ignored

In [ ]:
x_pt=torch.tensor([[25,2],[5,26],[3,7]])
x_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [ ]:
x_pt.T #more pythonic

tensor([[25,  5,  3],
        [ 2, 26,  7]])

In [ ]:
x_tf=tf.Variable([[25,2],[5,26],[3,7]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32_ref>

In [ ]:
tf.transpose(x_tf)

<tf.Tensor 'transpose:0' shape=(2, 3) dtype=int32>

BASIC TENSOR ARITHMETIC

In [ ]:
import numpy as np
import torch
import matplotlib.pyplot as plt
%tensorflow_version 1.x
import tensorflow as tf

TensorFlow 1.x selected.


In [ ]:
x=np.array([[25,2],[5,26],[3,7]])

In [ ]:
x*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [ ]:
x+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [ ]:
x*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [ ]:
x_pt=torch.tensor([[25,2],[5,26],[3,7]])

In [ ]:
x_pt*2+2 #python operators are overloaded, so we use torch.mul or torch.add()

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [ ]:
torch.add(torch.mul(x_pt, 2),2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [ ]:
x_tf=tf.Variable([[25,2],[5,26],[3,7]])

In [ ]:
x_tf*2+2 #here as well the python operators are overloaded

<tf.Tensor 'add:0' shape=(3, 2) dtype=int32>

In [ ]:
tf.add(tf.multiply(x_tf, 2),2)

<tf.Tensor 'Add_1:0' shape=(3, 2) dtype=int32>

HADAMARD PRODUCT OR ELEMENT-WISE PRODUCT

In [ ]:
X

NameError: ignored

In [ ]:
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [ ]:
a=x+2
a

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [ ]:
a+x

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [ ]:
a*x

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [ ]:
#with pytorch

In [ ]:
a_pt = x_pt +2
a_pt

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [ ]:
a_pt+x_pt

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [ ]:
a_pt*x_pt

tensor([[675,   8],
        [ 35, 728],
        [ 15,  63]])

In [ ]:
#with tensorflow

In [ ]:
a_tf=x_tf+2

In [ ]:
a_tf

<tf.Tensor 'add_2:0' shape=(3, 2) dtype=int32>

In [ ]:
a_tf+x_tf

<tf.Tensor 'add_3:0' shape=(3, 2) dtype=int32>

In [ ]:
a_tf*x_tf

<tf.Tensor 'mul_2:0' shape=(3, 2) dtype=int32>

TENSOR REDUCTION

In [ ]:
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [ ]:
x.sum()

68

In [ ]:
torch.sum(x_pt)

tensor(68)

In [ ]:
tf.reduce_sum(x_tf)

<tf.Tensor 'Sum:0' shape=() dtype=int32>

In [ ]:
#can also be done along one specific axis alone, e.g.:
x.sum(axis=0) # summing all rows

array([33, 35])

In [ ]:
x.sum(axis=1) # summing all columns

array([27, 31, 10])

In [ ]:
#pytorch
torch.sum(x_pt,0)

tensor([33, 35])

In [ ]:
tf.reduce_sum(x_tf,1)

<tf.Tensor 'Sum_1:0' shape=(3,) dtype=int32>

THE DOT PRODUCT

In [ ]:
x=np.array([25,2,5])
x

array([25,  2,  5])

In [ ]:
y= np.array([0,1,2])
y

array([0, 1, 2])

In [ ]:
25*0+2*1+5*2

12

In [ ]:
np.dot(x,y) 

12

In [ ]:
x_pt= torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [ ]:
y_pt = torch.tensor([0,1,2])
y_pt

tensor([0, 1, 2])

In [ ]:
np.dot(x_pt,y_pt)

12

In [ ]:
torch.dot(torch.tensor([25,2,5.]), torch.tensor([0,1,2.]))

tensor(12.)

In [ ]:
x_tf= tf.Variable([25,2,5])
x_tf

<tf.Variable 'Variable_1:0' shape=(3,) dtype=int32_ref>

In [ ]:
y_tf= tf.Variable([0,1,2])
y_tf

<tf.Variable 'Variable_2:0' shape=(3,) dtype=int32_ref>

In [ ]:
tf.reduce_sum(tf.multiply(x_tf,y_tf))

<tf.Tensor 'Sum:0' shape=() dtype=int32>

QUICK QUESTIONS ON COMMON TENSOR OPERATIONS

In [ ]:
y=np.array([[42,4,7,99],[-99,-3,17,22]])
y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [ ]:
y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [ ]:
a= np.array([[25,10],[-2,1]])
a

array([[25, 10],
       [-2,  1]])

In [ ]:
b=np.array([[-1,7],[10,8]])
b

array([[-1,  7],
       [10,  8]])

In [ ]:
a*b

array([[-25,  70],
       [-20,   8]])

In [ ]:
w_pt= torch.tensor([-1,2,-2])
w_pt

tensor([-1,  2, -2])

In [ ]:
t_pt= torch.tensor([5,10,0])
t_pt

tensor([ 5, 10,  0])

In [ ]:
np.dot(w_pt,t_pt)

15

In [2]:
import numpy as np
import torch
import matplotlib.pyplot as plt
%tensorflow_version 1.x
import tensorflow as tf

TensorFlow 1.x selected.


FORBENIUS NORM

In [ ]:
X =np.array([[1,2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [ ]:
(1**2+2**2+3**2+4**2)**(1/2)

5.477225575051661

In [ ]:
np.linalg.norm(X) #same function as for L2 norm

5.477225575051661

In [ ]:
X_pt=torch.tensor([[1,2],[3,4.]]) #torch.norm requires float

In [ ]:
torch.norm(X_pt)

tensor(5.4772)

In [ ]:
X_tf=tf.Variable([[1,2],[3,4.]]) #tf.norm also requires float

In [ ]:
tf.norm(X_tf)

<tf.Tensor 'norm/Squeeze:0' shape=() dtype=float32>

MATRIX MULTIPLICATION (WITH A VECTOR)

In [ ]:
A=np.array([[3,4],[5,6],[7,8]])

In [ ]:
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
b=np.array([1,2])
b

array([1, 2])

In [ ]:
np.dot(A,b) #even though technically dot products are between vctors only

array([11, 17, 23])

In [ ]:
A_pt=torch.tensor([[3,4],[5,6],[7,8]])
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [ ]:
b_pt=torch.tensor([1,2])
b_pt

tensor([1, 2])

In [ ]:
torch.matmul(A_pt,b_pt) #like np.dot(), automatically infers dims in order to perform the dot product, matvec or matrix multiplication

tensor([11, 17, 23])

In [ ]:
A_tf=tf.Variable([[3,4],[5,6],[7,8]])
A_tf

<tf.Variable 'Variable_2:0' shape=(3, 2) dtype=int32_ref>

In [ ]:
b_tf=tf.Variable([1,2])
b_tf

<tf.Variable 'Variable_3:0' shape=(2,) dtype=int32_ref>

In [ ]:
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor 'MatVec/Squeeze:0' shape=(3,) dtype=int32>

MATRIX INTO MATRIX

In [ ]:
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
B=np.array([[1,9],[2,0]])
B

array([[1, 9],
       [2, 0]])

In [ ]:
np.dot(A,B)

array([[11, 27],
       [17, 45],
       [23, 63]])

AB is not equal to BA. Therefore, it will cause a mismatch error

In [ ]:
#np.dot(B,A)

In [ ]:
B_pt= torch.from_numpy(B) #much cleaner than tf conversion
B_pt

tensor([[1, 9],
        [2, 0]])

In [ ]:
#another neat way to create tensor with transposition
B_pt=torch.tensor([[1,9],[2,0]]).T
B_pt

tensor([[1, 2],
        [9, 0]])

In [ ]:
torch.matmul(A_pt,B_pt)

tensor([[39,  6],
        [59, 10],
        [79, 14]])

In [ ]:
B_tf=tf.convert_to_tensor(B,dtype=tf.int32)
B_tf
                          

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [ ]:
tf.matmul(A_tf,B_tf)

<tf.Tensor 'MatMul:0' shape=(3, 2) dtype=int32>

SYMETRIC MATRICES

In [3]:
x_sym=np.array([[0,1,2],[1,7,8],[2,8,9]])
x_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [4]:
x_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [5]:
x_sym.T==x_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

IDENTITY MATRIX

In [6]:
i=torch.tensor([[1,0,0],[0,1,0],[0,0,1]])
i

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [7]:
x_pt=torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [8]:
torch.matmul(i,x_pt)

tensor([25,  2,  5])

MATRIX INVERSION

In [9]:
x=np.array([[4,2],[-5,-3]])
x

array([[ 4,  2],
       [-5, -3]])

In [10]:
xinv=np.linalg.inv(x)

In [11]:
xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [12]:
y=np.array([4,-7])
y

array([ 4, -7])

In [13]:
w=np.dot(xinv,y)
w

array([-1.,  4.])

In [14]:
np.dot(x,w)

array([ 4., -7.])

IN PYTORCH AND TENSORFLOW

In [18]:
torch.inverse(torch.tensor([[4,2],[-5,-3.]])) #float type

tensor([[ 1.5000,  1.0000],
        [-2.5000, -2.0000]])

In [19]:
tf.linalg.inv(tf.Variable([[4,2],[-5,-3.]])) #float type

<tf.Tensor 'MatrixInverse:0' shape=(2, 2) dtype=float32>